# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-19 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
